#!/usr/bin/env bash
# 남은 미결 — **단일 레인**. 과다구독하면 above(이송)에서 정체해 clamp 까지 못 간다.
set -u
source /dev/stdin <<< "$(sed -n '/^PY=/,/^}/p' sweep_clamp.sh)"
# (1) 대조군: 기구학 구동만으로 되는가, 플랜지 제거도 필요했나
run_one g3_kin125_flangeON WALL_KINEMATIC=1 CLAMP_TARGET_MM=-12.5 LEFTWALL_FLANGE_CONTACT=1 WALL_CLOSE_MMPS=8 HOLD_THROUGH_CLAMP=0
# (2) 깊이 한계: -13.5 가 통과했으니 더 내려가 본다
run_one g7_kin145 WALL_KINEMATIC=1 CLAMP_TARGET_MM=-14.5 LEFTWALL_FLANGE_CONTACT=0 WALL_CLOSE_MMPS=8 HOLD_THROUGH_CLAMP=0
run_one g8_kin135_r2 WALL_KINEMATIC=1 CLAMP_TARGET_MM=-13.5 LEFTWALL_FLANGE_CONTACT=0 WALL_CLOSE_MMPS=8 HOLD_THROUGH_CLAMP=0
run_one g9_kin155 WALL_KINEMATIC=1 CLAMP_TARGET_MM=-15.5 LEFTWALL_FLANGE_CONTACT=0 WALL_CLOSE_MMPS=8 HOLD_THROUGH_CLAMP=0
run_one g10_kin125_flangeON_r2 WALL_KINEMATIC=1 CLAMP_TARGET_MM=-12.5 LEFTWALL_FLANGE_CONTACT=1 WALL_CLOSE_MMPS=8 HOLD_THROUGH_CLAMP=0
