#!/usr/bin/env bash
# 힘제어로 푸는 길 — 단일 레인. 어젯밤 미검증으로 남은 두 축을 제대로 본다.
#   (1) 반사 관성: 런타임 API 로 확실히 적용 (MJCF 경로는 검증 안 됐었다)
#   (2) IPC 소프트 구속 강성: 레인 E 는 파일 경합으로 전부 죽어 결과가 없다
set -u
source /dev/stdin <<< "$(sed -n '/^PY=/,/^}/p' sweep_clamp.sh)"
run_one h1_arm100     WALL_ARMATURE=100 LEFTWALL_FLANGE_CONTACT=1 CLAMP_TARGET_MM=-12.5 WALL_CLOSE_MMPS=8 WALL_FORCE_LIM_N=100 HOLD_THROUGH_CLAMP=0
run_one h2_arm1000    WALL_ARMATURE=1000 LEFTWALL_FLANGE_CONTACT=1 CLAMP_TARGET_MM=-12.5 WALL_CLOSE_MMPS=8 WALL_FORCE_LIM_N=100 HOLD_THROUGH_CLAMP=0
run_one h3_cs10000    IPC_CONSTRAINT_STRENGTH=10000 WALL_ARMATURE=100 LEFTWALL_FLANGE_CONTACT=1 CLAMP_TARGET_MM=-12.5 WALL_CLOSE_MMPS=8 WALL_FORCE_LIM_N=100 HOLD_THROUGH_CLAMP=0
run_one h4_arm1000_kv2000 WALL_ARMATURE=1000 WALL_KV=2000 LEFTWALL_FLANGE_CONTACT=1 CLAMP_TARGET_MM=-12.5 WALL_CLOSE_MMPS=8 WALL_FORCE_LIM_N=100 HOLD_THROUGH_CLAMP=0
